version: '3.6'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - mysql_service
    ports:
      - "3306:3306"
  redis:
    image: "redis:alpine"
    networks:
      - redis_service
  api:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "true"
    networks:
      - mysql_service
      - redis_service
      - api_service
  
networks:
  mysql_service:
  redis_service:
  web_service:
  api_service:
    name: shared-network
