services:
  web:
    build: .
    ports:
      - "8080:80"
    # nginx:
    #   image: "nginx:latest"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data:/usr/share/nginx/html
    command: [nginx-debug, '-g', 'daemon off;']